### ISSUE TITLE
Infura links in truffle.js do not work

### ISSUE THREAD

**Issue by mlekena** [iExecBlockchainComputing/price-feed-doracle#2]
It would seem that the Infura links listed in the truffle.js file no longer work. I believe the security token (project secret token) is no longer valid. Im not sure if its supposed to work regardless of who pulled the file but it may be better to have users either create their own tokens or perhaps this project should be put on CICD and the api checked so that action can be taken when the api key expires/fails/is revoked.

The response I got from calling ` MNEMONIC=<YOUR_PRIVATE_KEY> ./node_modules/.bin/truffle migrate --network kovan`
```
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/home/mlekena/Dev/iexec-work/price-feed/smart-contract/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/web3/node_modules/web3-core-helpers/src/errors.js:42:1)
    at t.InvalidResponse [as onreadystatechange] (/home/mlekena/Dev/iexec-work/price-feed/smart-contract/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/web3/node_modules/web3-providers-http/src/index.js:92:1)
    at t._a [as dispatchEvent] (/home/mlekena/Dev/iexec-work/price-feed/smart-contract/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:27:61)
    at t.dispatchEvent [as _setReadyState] (/home/mlekena/Dev/iexec-work/price-feed/smart-contract/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
    at t._setReadyState [as _onHttpRequestError] (/home/mlekena/Dev/iexec-work/price-feed/smart-contract/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:349:1)
    at ClientRequest._onHttpRequestError (/home/mlekena/Dev/iexec-work/price-feed/smart-contract/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:252:47)
    at ClientRequest.emit (events.js:209:13)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:209:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

```

**Comment by mlekena** [comment]
Alright, this might have been a no0b mistake. To sanity check myself, I reverted the change locally in which I replaced the API key with my own and fired the migrate call and this time around it work.

I may have been to preemptive on creating this Issue.
